name: 'ggm_dwh'
version: '1.0.0'
config-version: 2
profile: ggm_dwh

models:
  ggm_dwh:
    raw:
      +schema: raw
      +materialized: table
      +tags: "raw"
    stg:
      +schema: stg
      +materialized: view
      +tags: "bronze"
    ggm:
      +schema: ggm
      +materialized: table
      +tags: "silver"
    dm:
      +schema: dm
      +materialized: view
      +tags: "gold"

seeds:
  ggm_dwh:
    schema: raw